import { useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { api } from '../api'
import type { Finding } from '../types'

export function FindingDetailPage() {
  const { findingId = '' } = useParams()
  const [finding, setFinding] = useState<Finding | null>(null)
  const [error, setError] = useState<string | null>(null)
  const [saving, setSaving] = useState(false)
  useEffect(() => { api.getFinding(findingId).then(setFinding).catch((err: Error) => setError(err.message)) }, [findingId])
  if (error) return <div className="empty-state"><h1>Finding unavailable</h1><p>{error}</p><Link to="/findings">Back to findings</Link></div>
  if (!finding) return <div className="empty-state"><h1>Finding not found</h1><p>This finding may be resolved or outside the active workspace.</p><Link to="/findings">Back to findings</Link></div>
  const severity = finding.severity || 'Low'
  const currentStatus = finding.status || (finding.verified ? 'open' : 'triaged')
  const findingIdentifier = finding.fingerprint || finding.check_id || findingId
  async function changeStatus(status: 'open' | 'triaged' | 'ignored') { setSaving(true); try { const updated = await api.updateFindingStatus(findingIdentifier, status); setFinding(updated) } catch (err) { setError(err instanceof Error ? err.message : String(err)) } finally { setSaving(false) } }
  return <div className="finding-detail-page"><div className="detail-breadcrumb"><Link to="/findings">← Findings</Link><span>/</span><span className="mono">{findingId}</span></div><header className="finding-detail-header"><div><div className="detail-badges"><span className={`severity-label ${severity.toLowerCase()}`}><i />{severity}</span><span className={`finding-status ${currentStatus}`}>{currentStatus}</span><span className="category-label">{finding.kind || 'Observation'}</span></div><h1>{finding.title}</h1><p>{finding.target_id || 'Unknown target'} · detected {finding.detected_at ? new Date(finding.detected_at).toLocaleString() : 'recently'}</p></div><div className="detail-actions"><button className="btn ghost" disabled={saving || currentStatus === 'triaged'} onClick={() => changeStatus('triaged')}>Mark triaged</button><button className="btn ghost" disabled={saving || currentStatus === 'ignored'} onClick={() => changeStatus('ignored')}>Ignore</button></div></header><div className="detail-grid"><main><section className="panel detail-section"><h2>What we found</h2><p>{finding.description || 'The scanner recorded a security finding on the monitored target.'}</p><div className="location-box"><span className="eyebrow">Affected location</span><code>{finding.url || 'Target root'}</code></div></section><section className="panel detail-section"><h2>Evidence</h2><pre className="evidence-block">{finding.evidence || 'No additional evidence was returned.'}</pre><div className="evidence-meta"><span>{finding.verified ? '✓ Verified finding' : 'Observed during scan'}</span><span>Check ID: <code>{finding.check_id || finding.fingerprint || findingId}</code></span></div></section><section className="panel detail-section"><h2>How to fix</h2><p>{finding.remediation || 'Review the affected endpoint and rerun the audit after applying a fix.'}</p></section></main><aside><section className="panel detail-side"><span className="eyebrow">Finding metadata</span><div className="meta-row"><span>Target</span><strong>{finding.target_id || 'Unknown'}</strong></div><div className="meta-row"><span>Category</span><strong>{finding.kind || 'Observation'}</strong></div><div className="meta-row"><span>Confidence</span><strong className="ok-text">{finding.confidence_level || (finding.verified ? 'Verified' : 'Unverified')}</strong></div><div className="meta-row"><span>Fingerprint</span><strong className="mono">{finding.fingerprint || '—'}</strong></div></section><section className="callout safety-note"><strong>Evidence is redacted</strong><p>Secrets, cookies and sensitive user data are never included in findings.</p></section></aside></div></div>
}
