import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { api } from '../api'
import type { ScanListItem } from '../types'
type Ops = { queued: number; workers: number; active: ScanListItem[]; recent_failures: ScanListItem[] }
export function OperationsPage() {
  const [data, setData] = useState<Ops | null>(null); const [error, setError] = useState<string | null>(null); const [retrying, setRetrying] = useState(false)
  const refresh = () => api.operations().then(setData).catch((err: Error) => setError(err.message))
  useEffect(() => { refresh(); const timer = window.setInterval(refresh, 15000); return () => window.clearInterval(timer) }, [])
  const retryLatest = async () => { const scan = data?.recent_failures[0]; if (!scan) return; setRetrying(true); try { await api.retryScan(scan.id); await refresh() } catch (err) { setError(err instanceof Error ? err.message : String(err)) } finally { setRetrying(false) } }
  return <div className="dashboard"><header className="page-header targets-header"><div><span className="eyebrow">Monitor / Operations</span><h1>Scanner operations</h1><p>Track active work and recover from recent failures.</p></div><div><Link className="btn" to="/scan">+ New audit</Link>{data?.recent_failures.length ? <button className="btn ghost" type="button" onClick={retryLatest} disabled={retrying}>{retrying ? 'Retrying…' : 'Retry latest'}</button> : null}</div></header>{error && <div className="callout error-note">Could not load operations: {error}</div>}<section className="history-summary"><div><span className="label">Queued</span><strong>{data?.queued ?? '—'}</strong><small>Waiting for a worker</small></div><div><span className="label">Workers</span><strong>{data?.workers ?? '—'}</strong><small>Available scanner workers</small></div><div><span className="label">Active scans</span><strong>{data?.active.length ?? '—'}</strong><small>Currently processing</small></div><div><span className="label">Recent failures</span><strong>{data?.recent_failures.length ?? '—'}</strong><small>Last 10 failed runs</small></div></section><section className="panel activity-panel"><div className="panel-heading"><h2>Active scans</h2></div><div className="activity-list">{!data ? <p className="empty">Loading operations…</p> : data.active.length ? data.active.map((scan) => <Link className="activity-row" to={`/scans/${scan.id}`} key={scan.id}><span className="activity-status running" /><div><strong>{scan.target_id}</strong><small>{scan.status} · {scan.stage?.current || 'Queued'}</small></div></Link>) : <p className="empty">No active scans.</p>}</div></section><section className="panel activity-panel"><div className="panel-heading"><h2>Recent failures</h2></div><div className="activity-list">{!data ? <p className="empty">Loading failures…</p> : data.recent_failures.length ? data.recent_failures.map((scan) => <Link className="activity-row" to={`/scans/${scan.id}`} key={scan.id}><span className="activity-status warn" /><div><strong>{scan.target_id}</strong><small>{new Date(scan.created_at).toLocaleString()}</small></div></Link>) : <p className="empty">No recent failures.</p>}</div></section></div>
}
