import { useEffect, useState, type FormEvent } from 'react'
import { Link } from 'react-router-dom'
import { api } from '../api'
import type { Target } from '../types'

type TargetRow = { name: string; url: string; environment: string; score: number; findings: number; lastAudit: string; status: 'Healthy' | 'Needs attention' }
export function TargetsPage() {
  const [targets, setTargets] = useState<TargetRow[]>([]); const [showForm, setShowForm] = useState(false); const [name, setName] = useState(''); const [url, setUrl] = useState(''); const [environment, setEnvironment] = useState('Production'); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [envFilter, setEnvFilter] = useState('All')
  const [query, setQuery] = useState('')
  useEffect(() => { let disposed = false; const refresh = () => api.listTargets().then((items: Target[]) => { if (disposed) return; setTargets(items.map((item) => { const findings = item.last_scan_summary?.findings || 0; const score = item.last_scan_status === 'completed' ? Math.max(0, 100 - findings * 5) : 0; return { name: item.base_url.replace(/^https?:\/\//, '').split('.')[0], url: item.base_url, environment: item.environment || 'Production', score, findings, lastAudit: item.last_scan_at ? new Date(item.last_scan_at).toLocaleString() : 'Not audited yet', status: findings ? 'Needs attention' : 'Healthy' } })); setError(null) }).catch((err: Error) => { if (!disposed) setError(err.message) }).finally(() => { if (!disposed) setLoading(false) }); refresh(); const timer = window.setInterval(refresh, 15000); return () => { disposed = true; window.clearInterval(timer) } }, [])
  async function addTarget(event: FormEvent) { event.preventDefault(); if (!name || !url) return; try { const saved = await api.addTarget({ base_url: url, environment, trusted_local: false }) as Target; setTargets((current) => [{ name, url: saved.base_url, environment: saved.environment || environment, score: 100, findings: 0, lastAudit: 'Not audited yet', status: 'Healthy' }, ...current]); setName(''); setUrl(''); setShowForm(false); setError(null) } catch (err) { setError(err instanceof Error ? err.message : String(err)) } }
  const visible = targets.filter((target) => (envFilter === 'All' || target.environment === envFilter) && `${target.name} ${target.url}`.toLowerCase().includes(query.toLowerCase()))
  return <div className="targets-page">
    <header className="page-header targets-header"><div><span className="eyebrow">Monitor / Targets</span><h1>Your targets</h1><p>Manage the websites and APIs you want to continuously audit.</p></div><button className="btn" onClick={() => setShowForm(true)}>+ Add target</button></header>
    {error && <div className="callout error-note">{error}</div>}<div className="target-toolbar"><div className="search-box"><span>⌕</span><input placeholder="Search targets..." value={query} onChange={(event) => setQuery(event.target.value)} /></div><div className="filter-pills"><button className={`filter ${envFilter === 'All' ? 'active' : ''}`} onClick={() => setEnvFilter('All')}>All <b>{targets.length}</b></button><button className={`filter ${envFilter === 'Production' ? 'active' : ''}`} onClick={() => setEnvFilter('Production')}>Production <b>{targets.filter((target) => target.environment === 'Production').length}</b></button><button className={`filter ${envFilter === 'Staging' ? 'active' : ''}`} onClick={() => setEnvFilter('Staging')}>Staging <b>{targets.filter((target) => target.environment === 'Staging').length}</b></button></div></div>
    <section className="target-table panel">{loading ? <p className="empty">Loading targets…</p> : visible.length === 0 ? <p className="empty">No targets match these filters.</p> : <><div className="table-head"><span>Target</span><span>Environment</span><span>Security score</span><span>Last audit</span><span>Status</span><span /></div>{visible.map((target) => <div className="target-row" key={target.url}><div className="target-identity"><span className="site-favicon purple">{target.name[0].toUpperCase()}</span><div><strong>{target.name}</strong><small>{target.url}</small></div></div><span className="env-tag">{target.environment}</span><div className="score-cell"><div className="score-bar"><i style={{ width: `${target.score}%` }} /></div><strong className={target.score < 70 ? 'danger-text' : target.score < 85 ? 'warn-text' : 'ok-text'}>{target.score}</strong><small>/100</small></div><span className="last-audit">{target.lastAudit}</span><span className={`status-label ${target.status === 'Healthy' ? 'healthy' : 'attention'}`}><i />{target.status}{target.findings > 0 && <small>{target.findings} findings</small>}</span><Link className="row-action" to={`/scan?target=${encodeURIComponent(target.url)}`}>Audit →</Link></div>)}</>}</section>
    <div className="target-footer"><span><strong>{targets.length}</strong> targets in this workspace</span><span className="muted">Last synced just now</span></div>
    {showForm && <div className="modal-backdrop" onMouseDown={(event) => event.target === event.currentTarget && setShowForm(false)}><div className="modal panel"><button className="modal-close" onClick={() => setShowForm(false)}>×</button><span className="eyebrow">New target</span><h2>Add a website or API</h2><p className="muted">Only add assets you own or have permission to test.</p><form className="form" onSubmit={addTarget}><label>Target name<input value={name} onChange={(event) => setName(event.target.value)} placeholder="e.g. customer-portal" required /></label><label>Base URL<input type="url" value={url} onChange={(event) => setUrl(event.target.value)} placeholder="https://example.com" required /></label><label>Environment<select value={environment} onChange={(event) => setEnvironment(event.target.value)}><option>Production</option><option>Staging</option><option>Development</option></select></label><div className="modal-actions"><button type="button" className="btn ghost" onClick={() => setShowForm(false)}>Cancel</button><button className="btn" type="submit">Add target</button></div></form></div></div>}
  </div>
}
